### ISSUE TITLE
Verlihub chashes on OpenBSD-5.7 i386

### ISSUE THREAD

**Issue by mikekmv** [Verlihub/verlihub#95]
Verlihub chashes on liblua after 1-3 minutes uptime:
```
GNU gdb 6.3
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-unknown-openbsd5.7"...
(gdb) run
Starting program: /usr/local/bin/verlihub
 (0)                           2016-07-17 01:15:12 #                main - Configuration directory: /etc/verlihub
 (1)                           2016-07-17 01:15:12 #                cMySQL - Connecting to MySQL server _vhub @ localhost / kmvhub using charset utf8
 (0)                           2016-07-17 01:15:12 #                cVHPluginMgr - using plugins in: /etc/verlihub/plugins
 (0)                           2016-07-17 01:15:12 #                cVHPluginMgr - ------------------------
 (0)                           2016-07-17 01:15:12 #                tCache - 19 items preloaded.
 (0)                           2016-07-17 01:15:12 #                tCache - 0 items preloaded.
 (0)                           2016-07-17 01:15:12 #                cVHPluginMgr - Open dir: /etc/verlihub/plugins/
 (0)                           2016-07-17 01:15:13 #                cVHPluginMgr - OnPluginLoad: Plugman
 (0)                           2016-07-17 01:15:13 #                cVHPluginMgr - OnPluginLoad: Lua
 (0)                           2016-07-17 01:15:13 #                PluginBase - (Lua) Opening directory: /etc/verlihub/scripts/
 (0)                           2016-07-17 01:15:15 #                cVHPluginMgr - OnPluginLoad: Python
PY: Autoload, loading scripts from directory: /etc/verlihub/scripts/
 (0)                           2016-07-17 01:15:15 #                cVHPluginMgr - OnPluginLoad: ForbiddenWords
 (0)                           2016-07-17 01:15:16 #                cVHPluginMgr - OnPluginLoad: Stats
 (0)                           2016-07-17 01:15:16 #                cVHPluginMgr - OnPluginLoad: IPLog
 (0)                           2016-07-17 01:15:16 #                cServerDC - Listening for connections on 0.0.0.0:4111 TCP

Program received signal SIGSEGV, Segmentation fault.
0x0fd01c75 in strlen (str=0x7ae98fcc 'Я' <repeats 52 times> <Address 0x7ae99000 out of bounds>)
    at /usr/src/lib/libc/string/strlen.c:39
39              for (s = str; *s; ++s)
Current language:  auto; currently c
(gdb) backtrace full
#0  0x0fd01c75 in strlen (str=0x7ae98fcc 'Я' <repeats 52 times> <Address 0x7ae99000 out of bounds>)
    at /usr/src/lib/libc/string/strlen.c:39
        s = 0x7ae99000 <Address 0x7ae99000 out of bounds>
#1  0x0eac361c in lua_pushstring () from /usr/local/lib/liblua5.1.so.5.1
No symbol table info available.
#2  0x0b843395 in nVerliHub::nLuaPlugin::cLuaInterpreter::CallFunction (this=0x8373e720, func=0x2b820490 "VH_OnTimer",
    args=0xcfbe815c, conn=0x0) at /root/src/verlihub/plugins/lua/cluainterpreter.cpp:274
        i = 2062127052
        result = Variable "result" is not available.
(gdb) info registers
eax            0x7ae99000       2062127104
ecx            0x8373e720       -2089556192
edx            0x7ae98fcc       2062127052
ebx            0x2eac18b4       783030452
esp            0xcfbe7f28       0xcfbe7f28
ebp            0xcfbe7f38       0xcfbe7f38
esi            0x7ae98fcc       2062127052
edi            0x83e99a00       -2081842688
eip            0xfd01c75        0xfd01c75
eflags         0x210216 2163222
cs             0x2b     43
ss             0x33     51
ds             0x33     51
es             0x33     51
fs             0x5b     91
gs             0x63     99
(gdb) x/16i $pc
0xfd01c75 <strlen+21>:  cmpb   $0x0,(%eax)
0xfd01c78 <strlen+24>:  jne    0xfd01c72 <strlen+18>
0xfd01c7a <strlen+26>:  sub    %edx,%eax
0xfd01c7c <strlen+28>:  leave
0xfd01c7d <strlen+29>:  ret
0xfd01c7e <strlen+30>:  nop
0xfd01c7f <strlen+31>:  nop
0xfd01c80 <strncmp>:    push   %ebx
0xfd01c81 <strncmp+1>:  mov    0x8(%esp),%eax
0xfd01c85 <strncmp+5>:  mov    0xc(%esp),%ecx
0xfd01c89 <strncmp+9>:  mov    0x10(%esp),%edx
0xfd01c8d <strncmp+13>: test   %edx,%edx
0xfd01c8f <strncmp+15>: jmp    0xfd01c95 <L2>
0xfd01c91 <strncmp+17>: nop
0xfd01c92 <L1>: inc    %eax
0xfd01c93 <L1+1>:       inc    %ecx
(gdb) thread apply all backtrace

Thread 1 (thread 1018774):
#0  0x0fd01c75 in strlen (str=0x7ae98fcc 'Я' <repeats 52 times> <Address 0x7ae99000 out of bounds>)
    at /usr/src/lib/libc/string/strlen.c:39
#1  0x0eac361c in lua_pushstring () from /usr/local/lib/liblua5.1.so.5.1
#2  0x0b843395 in nVerliHub::nLuaPlugin::cLuaInterpreter::CallFunction (this=0x8373e720, func=0x2b820490 "VH_OnTimer",
    args=0xcfbe815c, conn=0x0) at /root/src/verlihub/plugins/lua/cluainterpreter.cpp:274
#3  0x0b844bf6 in nVerliHub::nLuaPlugin::cpiLua::CallAll (this=0x81fb9000, fncname=0x2b820490 "VH_OnTimer", args=0xcfbe815c,
    conn=0x0) at /root/src/verlihub/plugins/lua/cpilua.cpp:233
#4  0x0b847129 in nVerliHub::nLuaPlugin::cpiLua::OnTimer (this=0x81fb9000, msec=1468707636245)
    at /root/src/verlihub/plugins/lua/cpilua.cpp:819
#5  0x065d45bd in nVerliHub::nPlugin::tVHCBL_R1Type<long long>::CallOne (this=0xcfbea0d8, pi=Variable "pi" is not available.
) at cvhpluginmgr.h:125
#6  0x065d4188 in nVerliHub::nPlugin::cVHCBL_Base::CallOne (this=0xcfbea0d8, pi=0x81fb9000) at cvhpluginmgr.h:74
#7  0x0651003f in nVerliHub::nPlugin::cCallBackList::ufCallOne::operator() (this=0xcfbe821c, pi=0x81fb9000)
    at /root/src/verlihub/src/ccallbacklist.cpp:51
#8  0x065100a8 in nVerliHub::nPlugin::cCallBackList::CallAll (this=0xcfbea0d8) at stl_algo.h:159
#9  0x065b94ee in nVerliHub::nSocket::cServerDC::OnTimer (this=0xcfbe85d4, now=@0xcfbe85fc) at cvhpluginmgr.h:129
#10 0x0650239c in nVerliHub::nSocket::cAsyncSocketServer::OnTimerBase (this=0xcfbe85d4, now=@0xcfbe85fc)
    at /root/src/verlihub/src/casyncsocketserver.cpp:301
#11 0x065036d8 in nVerliHub::nSocket::cAsyncSocketServer::run (this=0xcfbe85d4)
    at /root/src/verlihub/src/casyncsocketserver.cpp:117
#12 0x164363ad in main (argc=2072001964, argv=0xcfbea564) at /root/src/verlihub/src/verlihub.cpp:226
```
It worked good on OpenBSD-5.3 and 5.4 a few years.
Major change is time_t which 64bit now http://www.openbsd.org/55.html

**Comment by RoLex** [comment]
Please try to run hub now with this fix > https://github.com/verlihub/verlihub/commit/c5525ae

**Comment by mikekmv** [comment]
Fixed
